config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  resources :users, only: [:new, :create, :show]
  resources :invitations, only: [:new, :create]
  resources :events, only: [:new, :create, :show, :index]

  get 'sessions/new'
  post 'sessions/create'
  get 'sessions/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :hosting_user, foreign_key: 'hoster_id', class_name: 'User'

  has_many :invitations, foreign_key: 'event_id', dependent: :destroy
  has_many :invited_users, through: :invitations, source: 'invited_users'

  scope :upcomming, -> { where('date >= ? ', Date.today) }
  scope :past, -> { where('date < ? ', Date.today) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :invited_users, class_name: 'User', foreign_key: 'invited_user_id'
  belongs_to :invited_events, class_name: 'Event', foreign_key: 'event_id'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :hosting_events, foreign_key: 'hoster_id', class_name: 'Event'

  has_many :invitations, foreign_key: 'invited_user_id', dependent: :destroy
  has_many :invited_events, through: :invitations, source: 'invited_events'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include UsersHelper

  before_action :require_login

  def index
    @events = Event.all

    @upcoming_events = Event.upcomming
    @past_events = Event.past
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.hosting_events.build(event_params)
    @event.hoster_id = current_user.id

    if @event.save
      flash.notice = "Event #{@event.name} created!"
      redirect_to root_path
    else
      flash.now[:alert] = 'Invalid post'
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :date)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  include UsersHelper

  before_action :require_login

  def new
    @invitation = Invitation.new
  end

  def create
    @invitation = Invitation.new

    invitation_params

    if @invitation.save
      flash.notice = 'User invited successfully!'
      redirect_to events_path
    else
      flash.now[:alert] = 'Invitation could not be created, check the input information!'
      render :new
    end
  end

  private

  def invitation_params
    unless invitation_invited_user_check || invitation_event_check
      @invitation.invited_user_id = (User.find_by username: params[:invitation][:users][:username]).id
      @invitation.event_id = (Event.find_by name: params[:invitation][:events][:name]).id
      @event = Event.find_by name: params[:invitation][:events][:name]
    end
    @event
  end

  def invitation_invited_user_check
    (User.find_by username: params[:invitation][:users][:username]).nil?
  end

  def invitation_event_check
    (Event.find_by name: params[:invitation][:events][:name]).nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include UsersHelper

  before_action :require_logout, only: [:new]

  def new
    @user = User.new
  end

  def show; end

  def create
    @user = User.find_by(session_params)

    if @user
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: 'Logged in'
    else
      flash.now[:alert] = 'Invalid Username!'
      @user = User.new
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out'
  end

  private

  def session_params
    params.require(:user).permit(:username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  before_action :require_logout, only: [:new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save

    flash.notice = "User #{@user.username} created!"
    redirect_to root_path
  end

  def show
    @user = User.find(params[:id])

    @upcoming_events = Event.upcomming
    @past_events = Event.past
    @hosting_events = @user.hosting_events
  end

  private

  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def upcoming_events_check(event)
    'Upcoming events' unless event.empty?
  end

  def past_events_check(event)
    'Previous events' unless event.empty?
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  private

  def user_sign_in?
    session[:user_id].nil? ? false : true
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_login
    return if user_sign_in?

    flash.notice = 'You have to be logged in to access that page'
    redirect_to root_path
  end

  def require_logout
    redirect_to events_path if user_sign_in?
  end

  def hosting_event_check(event)
    'Events hosted by this user: ' unless event.empty?
  end

  def past_event_user_check(event)
    'Events this user attended to: ' unless event.empty?
  end

  def upcoming_event_user_check(event)
    'This user is coming to these events: ' unless event.empty?
  end
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/index.html.erb
<div class="container d-flex justify-content-center">
  <div class="w-50 pt-3">
    <h3><%= upcoming_events_check(@upcoming_events) %></h3>
    <% @upcoming_events.each do |event| %>
      <div class="card pb-0 mb-3">
        <div class="card-body pb-0 text-dark">
          <h5 class="card-title">Event: <%= event.name %></h5>
          <p class="card-text">Location: <%= event.location %><p>
          <p class="card-text">Date: <%= event.date %><p>
          <%= link_to event.hosting_user.username.capitalize, user_path(event.hosting_user), class: 'badge badge-light' %>
          <%= link_to 'Details', event_path(event), class: 'badge badge-dark' %>
        </div>
      </div>
    <% end %>

    <h3><%= past_events_check(@past_events) %></h3>
    <% @past_events.each do |event| %>
      <div class="card pb-0 mb-3">
        <div class="card-body pb-0 text-dark">
          <h5 class="card-title">Event: <%= event.name %></h5>
          <p class="card-text">Location: <%= event.location %><p>
          <p class="card-text">Date: <%= event.date %><p>
          <%= link_to event.hosting_user.username.capitalize, user_path(event.hosting_user), class: 'badge badge-light' %>
          <%= link_to 'Details', event_path(event), class: 'badge badge-dark' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="container mt-5 d-flex justify-content-center">
  <div class="w-25">
    <%= form_for @event do |e| %>
      <div class="form-group">
        <%= e.label :name %>
        <%= e.text_field :name, placeholder: 'Event name', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= e.label :location %>
        <%= e.text_field :location, placeholder: 'Event location', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= e.label :date %>
        <%= e.text_field :date, placeholder: 'Event date', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= e.submit 'Create event', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

<%= @event.errors.full_messages %>

app/views/events/show.html.erb
<div class='container d-flex justify-content-center'>
  <div class="w-50">
    <h3>List of invited people:</h3>
    <% @event.invited_users.each do |iu| %>
      <div class="card mb-3">
        <div class="card-body">
          <h5 class="card-title"><%= iu.username.capitalize %></h5>
          <h6 class="card-subtitle"><%= iu.email %></h6>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/invitations/new.html.erb
<div class="container mt-5 d-flex justify-content-center">
  <div class="w-50">
    <%= form_for @invitation do |i| %>
      <div class="form-group">
        <%= i.fields_for :users do |u| %>
          <%= u.label 'Input the name of the invited user' %>
          <%= u.text_field :username, placeholder: 'Username', class: 'form form-control' %>
        <% end %>
      </div>
      <div class="form-group">
        <%= i.fields_for :events do |e| %>
          <%= e.label 'Input the name of the select event' %>
          <%= e.text_field :name, placeholder: 'Event name', class: 'form form-control' %>
        <% end %>
      </div>
      <div class="form-group">
        <%= i.submit 'Submit', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- NO MESS AREA START -->
    <title>PrivateEvent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- NO MESS AREA END -->


    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>

  <body>
     <div class="d-flex justify-content-end my-2">
      <% if user_sign_in? %>
        <div class="mx-3">
          <%= link_to "Home", events_path, class: 'btn btn-primary' %>
        </div>
        <div class="mx-3">
          <%= link_to "Create invitation", new_invitation_path, class: 'btn btn-light' %>
        </div>
        <div class="mx-3">
          <%= link_to "Create new event", new_event_path, class: 'btn btn-light' %>
        </div>
        <div class="mx-3">
          <%= link_to current_user.username, user_path(current_user), class: 'btn btn-success' %>
        </div>
        <div class="my -3 ml-3 mr-5">
          <%= link_to "Logout", sessions_destroy_path, class: 'btn btn-warning' %>
        </div>
      <% else %>
        <div class="mx-3">
          <%= link_to "Home", events_path, class: 'btn btn-primary' %>
        </div>
        <div class="mx-3">
          <%= link_to "Log in", sessions_new_path, class: 'btn btn-success' %>
        </div>
        <div class=" ml-3 mr-5">
          <%= link_to "Sign up", new_user_path, class: 'btn btn-info' %>
        </div>
      <% end %>

     </div>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="container mt-5 d-flex justify-content-center">
  <div class="w-25">
    <% unless user_sign_in? %>
      <%= form_for @user do |u| %>
        <div class="form-group">
          <%= u.label :username %>
          <%= u.text_field :username, placeholder: 'Username', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= u.label :email %>
          <%= u.text_field :email, placeholder: 'Email', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= u.submit 'Submit', class: 'btn btn-primary' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container d-flex justify-content-center">
  <div class="w-50">

    <h3><%= hosting_event_check(@hosting_events) %></h3>
    <% @hosting_events.each do |event| %>
      <div class="card pb-0 mb-3">
        <div class="card-body pb-0 text-dark">
          <h5 class="card-title">Event: <%= event.name %></h5>
          <p class="card-text">Location: <%= event.location %><p>
          <p class="card-text">Date: <%= event.date %><p>
        </div>
      </div>
    <% end %>

    <h3 class="mt-3"><%= upcoming_event_user_check(@upcoming_events) %></h3>
    <% @upcoming_events.each do |event| %>
      <div class="card pb-0 mb-3">
        <div class="card-body pb-0 text-dark">
          <h5 class="card-title">Event: <%= event.name %></h5>
          <p class="card-text">Location: <%= event.location %><p>
          <p class="card-text">Date: <%= event.date %><p>
        </div>
      </div>
    <% end %>


    <h3 class="mt-3"><%= past_event_user_check(@upcoming_events) %></h3>
    <% @past_events.each do |event| %>
      <div class="card pb-0 mb-3">
        <div class="card-body pb-0 text-dark">
          <h5 class="card-title">Event: <%= event.name %></h5>
          <p class="card-text">Location: <%= event.location %><p>
          <p class="card-text">Date: <%= event.date %><p>
        </div>
      </div>
    <% end %>

  </div>
</div>